/*
ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ                                                                         บ
บ              Program  ED - A DATABASE MODELING TOOL                     บ
บ                                                                         บ
บ              EDKEY.H    Key Codes for non-alpha keys used in            บ
บ                         ED's various keyboard interpreters.             บ
บ                                                                         บ
บ              written by William A. Tolhurst                             บ
บ                                                                         บ
บ       This software is NOT Copyrighted.  Please feel free to use it     บ
บ       in any way you see fit, either in its entirety or in whatever     บ
บ       bits and pieces you need.  I, however, will not assume any re-    บ
บ       sponsibility for any aspect of its use, and do not claim suit-    บ
บ       ability for a particular purpose.  Enjoy!                         บ
บ                                                                         บ
บ       NOTE:  This statement does not affect the copyright status of     บ
บ              other software that accompanies it.  Please respect the    บ
บ              Copyright claims exercised by the other software authors.  บ
บ                                                                         บ
บ                                                                         บ
ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
*/

#define KEY_ESCAPE 27
#define KEY_ENTER 13
#define KEY_LINEFEED 10
#define KEY_TAB 9
#define KEY_BACKSPACE 8
#define KEY_PLUS 43
#define KEY_MINUS 45

#define ENHANCED_KEY 0

#define EKEY_LEFT 75
#define EKEY_RIGHT 77
#define EKEY_UP 72
#define EKEY_DOWN 80
#define EKEY_CTRL_LEFT 115
#define EKEY_CTRL_RIGHT 116
#define EKEY_CTRL_UP 141
#define EKEY_CTRL_DOWN 145
