/*
ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ                                                                         บ
บ              Program  ED - A DATABASE MODELING TOOL                     บ
บ                                                                         บ
บ              EDSCMODE.H Definitions of commands and functions for       บ
บ                         Scene Mode.                                     บ
บ                                                                         บ
บ              written by William A. Tolhurst                             บ
บ                                                                         บ
บ       This software is NOT Copyrighted.  Please feel free to use it     บ
บ       in any way you see fit, either in its entirety or in whatever     บ
บ       bits and pieces you need.  I, however, will not assume any re-    บ
บ       sponsibility for any aspect of its use, and do not claim suit-    บ
บ       ability for a particular purpose.  Enjoy!                         บ
บ                                                                         บ
บ       NOTE:  This statement does not affect the copyright status of     บ
บ              other software that accompanies it.  Please respect the    บ
บ              Copyright claims exercised by the other software authors.  บ
บ                                                                         บ
บ                                                                         บ
ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
*/

// Commands

#define CMD_IDLE 0
#define CMD_INITSYS 1
#define CMD_MOVE_VIEW 2
#define CMD_LOAD_OBJ_FILE 3
#define CMD_SELECT_OBJECT 4
#define CMD_ADD_OBJECT 5
#define CMD_DELETE_OBJECT 6
#define CMD_EDIT_OBJECT 7
#define CMD_OBJECT_MODE 8
#define CMD_STUDIO_MODE 9
#define CMD_EDIT_SYSPARMS 10
#define CMD_READ_SESSION 11
#define CMD_WRITE_SESSION 12
#define CMD_EXIT -1

//Move Functions
#define FUN_UP 0
#define FUN_DOWN 1
#define FUN_LEFT 2
#define FUN_RIGHT 3
#define FUN_IN 4
#define FUN_OUT 5
#define FUN_YAWLEFT 6
#define FUN_YAWRIGHT 7
#define FUN_PITCHUP 8
#define FUN_PITCHDOWN 9
#define FUN_ROLLLEFT 10
#define FUN_ROLLRIGHT 11

