/*
ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ                                                                         บ
บ             BkGlobs.H = globals for the BkGraph.C modules               บ
บ                                                                         บ
บ       Copyright 1988,1992 Christopher D. Watkins and Stephen B. Coy     บ
บ                                                                         บ
บ       ALL RIGHTS RESERVED.   This software is published, but is NOT     บ
บ         Public Domain and remains the propery of ALGORITHM, Inc.,       บ
บ   Christopher D. Watkins and Stephen B. Coy.  This software may not be  บ
บ  reproduced or integrated into other packages without the prior written บ
บ          consent of Christopher D. Watkins and Stephen B. Coy.          บ
บ                                                                         บ
ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
*/

int    XRes, YRes;
Word   MaxXRes, MaxYRes;
Word   MaxX, MaxY;
float  Asp;
Boolean PerspectivePlot;
float  Mx, My, Mz, ds;
Boolean Draw_Axis_And_Palette;
int    Angl, Tilt;
int Write_RAW_Data;
