rem Quiet - Rational Systems Credit
set DOS4G=quiet

ploteqn
rem Polygon Smooth
rem      (prepares polygons for a Phong Shader)
rem This version by
rem      Christopher D. Watkins and Stephen B. Coy
rem Based on the public domain Sandpaper III by
rem      Mike Schoenborn
type ploteqn1.raw | smooth > ploteqn1.bo
erase *.raw

ocean
rem Polygon Smooth
rem      (prepares polygons for a Phong Shader)
rem This version by
rem      Christopher D. Watkins and Stephen B. Coy
rem Based on the public domain Sandpaper III by
rem      Mike Schoenborn
type ocean.raw | smooth > ocean.bo
erase *.raw

cpm-mset
rem Polygon Smooth
rem      (prepares polygons for a Phong Shader)
rem This version by
rem      Christopher D. Watkins and Stephen B. Coy
rem Based on the public domain Sandpaper III by
rem      Mike Schoenborn
type cpmmset1.raw | smooth > cpmmset1.bo
erase *.raw

cpm-jset
rem Polygon Smooth
rem      (prepares polygons for a Phong Shader)
rem This version by
rem      Christopher D. Watkins and Stephen B. Coy
rem Based on the public domain Sandpaper III by
rem      Mike Schoenborn
type cpmjset1.raw | smooth > cpmjset1.bo
erase *.raw

quater
rem Polygon Smooth
rem      (prepares polygons for a Phong Shader)
rem This version by
rem      Christopher D. Watkins and Stephen B. Coy
rem Based on the public domain Sandpaper III by
rem      Mike Schoenborn
type dragon.raw | smooth > dragon.bo
cls
rem Polygon Smooth
rem      (prepares polygons for a Phong Shader)
rem This version by
rem      Christopher D. Watkins and Stephen B. Coy
rem Based on the public domain Sandpaper III by
rem      Mike Schoenborn
type revsolid.raw | smooth > revsolid.bo
erase *.raw

quater2
rem Polygon Smooth
rem      (prepares polygons for a Phong Shader)
rem This version by
rem      Christopher D. Watkins and Stephen B. Coy
rem Based on the public domain Sandpaper III by
rem      Mike Schoenborn
type dragon2.raw | smooth > dragon2.bo
cls
rem Polygon Smooth
rem      (prepares polygons for a Phong Shader)
rem This version by
rem      Christopher D. Watkins and Stephen B. Coy
rem Based on the public domain Sandpaper III by
rem      Mike Schoenborn
type revsol2.raw | smooth > revsol2.bo
erase *.raw

terrain
rem Polygon Smooth
rem      (prepares polygons for a Phong Shader)
rem This version by
rem      Christopher D. Watkins and Stephen B. Coy
rem Based on the public domain Sandpaper III by
rem      Mike Schoenborn
type terrain.raw | smooth > terrain.bo
erase *.raw
